version: '3.7'
services:
  db:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: storereceipts
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  api:
    build: ./server/
    container_name: api
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4000:4000'
  web:
    build: ./client/
    container_name: web
    depends_on:
      - db
      - api
    volumes:
      - ./client:/usr/src/app
    ports:
      - '3000:3000'
